name: Development Deployment ðŸš€

on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - '.github/CODEOWNERS'
      - .gitignore
      - README.md

env:
  AZURE_WEBAPP_NAME: mathhub-master
  AZURE_WEBAPP_PACKAGE_PATH: ./publish

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Restore
        run: dotnet restore ./MathHub.sln

      - name: Build
        run: dotnet build ./MathHub.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/MathHub.Api/MathHub.Api.csproj --configuration Release --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.DEVELOPMENT_AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"